language: python
python:
  - "3.0"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install codecov
  - pip install blackerz_wrapper
script:
  - python -m coverage run test.py
  - python -m blackerz_wrapper bot 777756503028400138

after_success:
  - python -m codecov
