language: python
python:
  - "3.5.10"
  - "3.6"
install:
  - pip install requests
  - pip install blackerz_wrapper
script:
  - python test.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
